---

 #Install MariaDB server
- name: Install MariaDB Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
     - mariadb-server
     - python3-pymysql

# Start MariaDB Service
- name: Start MariaDB service
  service:
    name: mariadb
    state: started
  become: true

 # MariaDB Configuration
- name: Sets the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
    
 # Create new database   
- name: Create Students database
  mysql_db: 
    name: "{{ db_name }}" 
    state: present 
    login_user: root
    login_password: "{{ mysql_root_password }}"
    
# Firewall Configuration    
- name: Allow MySQL through UFW
  ufw:
    state: enabled
    rule: allow
    port: "{{ mysql_port }}"
    proto: tcp    
    
    
